---
title: "Make Your Monday Even Brighter??"
output: 
  flexdashboard::flex_dashboard:
    social: ["menu" ]
    orientation: rows
    vertical_layout: scroll
    theme: bootstrap
    navbar:
      - { title: "About Me", href: "https://simonsayz.xyz", align: right }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(tidytext)
library(glue)
```

```{r}
p <- getwd()
df <- read_csv(paste(p, "/df2.csv", sep = ""))
# knitr::kable(head(df, 20))
```

Row
-----------------------------------------------------------------------

### Unique Jobs

```{r}
jobs_unique <- max(df$id)
valueBox(jobs_unique, icon = "fa-user-md")
```

###  Unique Industries 

```{r}
valueBox(2, icon = "fa-industry")
```

### Spam per Day

```{r}
# spam <- computeSpam()
valueBox(12,
         icon = "fa-trash",
         color = "primary")
```

Row 
-----------------------------------------------------------------------
  
### CHART 1
    
```{r}
df2 %>%
        unnest_tokens(word, description) %>% dim()
        anti_join(stop_words) %>%
        count(word, sort = TRUE) %>%
        mutate(word = fct_reorder(word, n)) %>%
        filter(!is.na(word)) %>%
        head(20) %>%
        ggplot(aes(word, n, fill = word)) +
        geom_col(show.legend = FALSE) +
        coord_flip() +
        labs(y = "count",
             x = "word",
             title = "1. Most Common Words in All Industries Industry")

```

### CHART 2
    
```{r}
# b_grams <- 
df %>%
        unnest_tokens(bigram,
                      description,
                      token = "ngrams",
                      n = 2) %>%
        count(bigram, sort = T) %>%
        separate(bigram, c("word1", "word2"), sep = " ") %>%
        filter(!word1 %in% stop_words$word) %>%
        filter(!word2 %in% stop_words$word) %>%
        filter(!is.na(word1)) %>%
        filter(!is.na(word2)) %>%
        unite(bigram, word1, word2, sep = " ") %>%
        mutate(bigram = fct_reorder(bigram, n)) %>%
        head(10) %>%
        ggplot(aes(bigram, n)) +
        geom_col() +
        coord_flip()

```

Column 
-----------------------------------------------------------------------
   
### DATASET

```{r}

DT::datatable(df, options = list(pageLength = 10))

```   


 
